import asyncio
import sys
import os
from mcp import ClientSession, StdioServerParameters
from mcp.client.stdio import stdio_client

# 确保这里的名字与你的服务器文件名一致
SERVER_SCRIPT = "../os_mcp/os_mcp_server.py"


async def run_tests():
    # 1. 配置服务器启动参数
    # 我们将 python 解释器作为命令，服务器脚本作为参数
    server_params = StdioServerParameters(
        command=sys.executable,
        args=[SERVER_SCRIPT],
        env=None  # 可以继承当前环境变量
    )

    print(f"🔌 Connecting to MCP Server: {SERVER_SCRIPT} ...")

    # 建立 stdio 连接
    async with stdio_client(server_params) as (read, write):
        async with ClientSession(read, write) as session:
            # 初始化握手
            await session.initialize()
            print("✅ Connected and Initialized!\n")

            # --- 定义一个辅助函数来模拟 'tool.invoke' ---
            async def invoke_tool(tool_name: str, args: dict):
                print(f"🛠️  Invoking: [ {tool_name} ]")
                print(f"   Args: {args}")
                try:
                    # 这就是标准的异步调用方式，等同于 await tool.coroutine(**args)
                    result = await session.call_tool(tool_name, arguments=args)

                    # 提取文本内容
                    output = result.content[0].text
                    print(f"   Example Output: {output[:1000]}..." if len(output) > 1000 else f"   Result: {output}")
                    print("   ✅ Success\n")
                    return output
                except Exception as e:
                    print(f"   ❌ Failed: {e}\n")

            # ==========================================
            # 开始测试 5 个工具
            # ==========================================
            tools = await session.list_tools()
            for tool in tools.tools:
                print(f"Name: {tool.name},")
                print(f"  -Description: {tool.description}")
                print(f"  -InputSchema: {tool.inputSchema}")


            # 1. 测试 get_system_info
            # 这里的目的是获取环境基础信息
            await invoke_tool("get_system_info", {})

            # 2. 测试 write_file
            # 我们先写一个文件，供后续读取测试
            test_filename = "mcp_test_doc.txt"
            test_content = "Hello! This is a test content generated by the Async MCP Client.\nTime to test I/O."
            await invoke_tool("write_file", {
                "path": test_filename,
                "content": test_content
            })

            # 3. 测试 read_file
            # 读取刚才写入的文件，验证内容
            read_result = await invoke_tool("read_file", {
                "path": test_filename
            })
            # 简单断言验证
            if "Async MCP Client" not in read_result:
                print("   ⚠️  Warning: File content mismatch!")

            # 4. 测试 append_environment_variable
            # 向 .env 文件追加变量
            await invoke_tool("append_environment_variable", {
                "key": "DEPLOY_ENV",
                "value": "staging_v2"
            })

            # 5. 测试 execute_command
            # 使用 echo 命令验证命令执行 (跨平台兼容)
            # 注意：由于我们在服务端使用了 shlex，不要使用复杂的管道符
            await invoke_tool("execute_command", {
                "command": "powershell echo '好好好，MCP Command Execution Works'"
            })

            await invoke_tool("execute_command", {
                "command": "ollama list"
            })
            await invoke_tool("execute_command", {
                "command": "python -V"
            })
            # 额外测试：测试 execute_command 的超时或错误处理 (可选)
            await invoke_tool("execute_command", {
                "command": "powershell sleep 2",
                "timeout": 1
            })



    print("🏁 All tests completed.")


if __name__ == "__main__":
    # 检查服务器文件是否存在
    if not os.path.exists(SERVER_SCRIPT):
        print(f"❌ Error: Server file '{SERVER_SCRIPT}' not found in current directory.")
        sys.exit(1)

    # 运行异步主循环
    try:
        asyncio.run(run_tests())
    except KeyboardInterrupt:
        print("\nClient stopped by user.")